/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f1f",
        "on-tertiary-fixed": "#1c1c18",
        "background": "#131313",
        "surface-dim": "#131313",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#3d2400",
        "error-container": "#93000a",
        "on-tertiary": "#31312c",
        "on-background": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed": "#ffddb6",
        "on-error": "#690005",
        "secondary-fixed-dim": "#ffb95a",
        "surface-container-high": "#2a2a2a",
        "outline": "#9f8e7a",
        "on-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#474742",
        "on-primary": "#452b00",
        "obsidian-surface": "#171717",
        "surface-variant": "#353534",
        "tertiary": "#d4d2cb",
        "surface": "#131313",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#ffb955",
        "secondary": "#ffb95a",
        "primary": "#ffc880",
        "on-tertiary-container": "#484743",
        "inverse-primary": "#835500",
        "on-secondary": "#462a00",
        "tertiary-container": "#b8b6b0",
        "tertiary-fixed": "#e5e2db",
        "surface-container-highest": "#353534",
        "on-primary-container": "#644000",
        "surface-tint": "#ffb955",
        "secondary-container": "#c68315",
        "on-surface-variant": "#d7c3ae",
        "primary-container": "#f5a623",
        "error": "#ffb4ab",
        "outline-variant": "#524534",
        "tertiary-fixed-dim": "#c9c6c0",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "soft-cream": "#EFE7D8",
        "surface-bright": "#3a3939",
        "on-secondary-fixed": "#2a1800",
        "glow-amber": "rgba(245, 166, 35, 0.15)",
        "on-primary-fixed": "#291800",
        "on-secondary-fixed-variant": "#643f00",
        "on-primary-fixed-variant": "#633f00",
        "primary-fixed": "#ffddb4"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Playfair Display", "serif"],
        "body": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
      }
    },
  },
  plugins: [],
}
